### ISSUE TITLE
can not get customer_id when logged-in customer click on downloadable link

### ISSUE THREAD

**Issue by rumbdev** [scandipwa/customer-downloadable-graphql#6]
**Prerequisites:**
tested on:
Scandipwa 5.4.0
Magento 2.4.3
but probably present in scandipwa 4 too

**Step to reproduce:**
- Buy a downloadable product that does not allow to share link (sharable: no). This option must be selected (product's downloadable section) before buying the product
- Log in as customer and try to download

**Expected result:**
being able to download

**Actual result:** 
download fails if "is sharable" is not selected because customer session is empty after clicking the controller ScandiPWA\CustomerDownloadableGraphQl\Controller\Download\Link

**DETAILS:**
I see a problem about how ScandiPWA manage the customer session in the customer's downloadable products section (when clicking the product-downloadable link).
The problem is that when a customer logs in (or when clicks "My downloadable" section) the customer_id is stored in the customer session and retrieved in `vendor/scandipwa/customer-graph-ql/src/Model/Customer/GetCustomer.php` via `$currentUserId = $context->getUserId();` note that here $context is `Magento\GraphQl\Model\Query\ContextInterface`.
Instead when trying to download a product that they've bought there is no customer session registered in SESSION (or at least the session is empty and customer_id is null) hence the download fails (except when the product's option "is sharable" is selected because the product can be downloaded even if a customer session is not present).
This happens because in `vendor/scandipwa/customer-downloadable-graphql/src/Controller/Download/Link.php` the `$session = $this->_getCustomerSession();` returns an empty customer_id. Note that here $context is `Magento\Framework\App\Action\Context`.

I'm trying to find a workaround but I can't use `Magento\GraphQl\Model\Query\ContextInterface;`  hence things get complicated.
Also note that the problem is not that we aren't logged in: the problem is that there is no customer session registered in the declared context `Magento\Framework\App\Action\Context` (or, again, if it is registered it is empty and customer_id is null).
The fact that the class `vendor/scandipwa/customer-downloadable-graphql/src/Controller/Download/Link.php` hasn't got a constructor does not allow to test changing the context via di (not sure that is a viable option though).

**Comment by carinadues** [comment]
Moved issue to https://github.com/scandipwa/scandipwa/issues/3826
